spring.application.name=Sora-index
spring.datasource.url=jdbc:postgresql://localhost:5432/sora_index
spring.datasource.username=postgres
spring.datasource.password=Sora0820

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true